#if os(macOS)
import Foundation
import OSLog

private let logger = Logger(subsystem: "com.mab.mira", category: "TokenStore")

/// Where the macOS thin client gets its API token.
///
/// The token is generated by mira-core's installer at
/// `~/.local/share/mira/token` and mirrored into `mira.yaml`'s `auth_token`.
/// Reading that path directly does NOT work in a sandboxed build: inside the
/// App Sandbox `FileManager.homeDirectoryForCurrentUser` resolves to the app's
/// container, so the lookup silently misses and every request goes out with no
/// Authorization header. Sandbox landed 2026-04-25, the direct read landed
/// 2026-05-30, so it has never worked in a sandboxed build.
///
/// Resolution order:
///   1. Keychain — the durable home once the token has been supplied once.
///   2. The token file — only reachable in an unsandboxed dev build, kept
///      because it makes a fresh `xcodebuild` run work with no manual step.
///   3. Nothing, and say so, so the caller can prompt instead of failing with
///      an unexplained 401.
enum TokenStore {

    private static let service = "com.mab.mira.apitoken"
    private static let account = "local-server"

    enum Source: Equatable {
        case keychain
        case file(String)
        case none
    }

    /// The token, plus where it came from. `nil` means the app has no token and
    /// must ask for one.
    static func load() -> (token: String, source: Source)? {
        if let t = readKeychain(), !t.isEmpty {
            return (t, .keychain)
        }
        if let (t, path) = readTokenFile(), !t.isEmpty {
            // Promote it so later launches do not depend on sandbox state.
            if save(t) { logger.info("token migrated from file into the keychain") }
            return (t, .file(path))
        }
        logger.warning("no API token found in keychain or on disk; requests will be unauthorised")
        return nil
    }

    @discardableResult
    static func save(_ token: String) -> Bool {
        let value = Data(token.trimmingCharacters(in: .whitespacesAndNewlines).utf8)
        var query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
        ]
        SecItemDelete(query as CFDictionary)
        query[kSecValueData as String] = value
        query[kSecAttrAccessible as String] = kSecAttrAccessibleAfterFirstUnlock
        let status = SecItemAdd(query as CFDictionary, nil)
        if status != errSecSuccess {
            logger.error("keychain write failed: \(status)")
            return false
        }
        return true
    }

    static func clear() {
        SecItemDelete([
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
        ] as CFDictionary)
    }

    // ── internals ─────────────────────────────────────────────────────────────

    private static func readKeychain() -> String? {
        var out: CFTypeRef?
        let status = SecItemCopyMatching([
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: service,
            kSecAttrAccount as String: account,
            kSecReturnData as String: true,
            kSecMatchLimit as String: kSecMatchLimitOne,
        ] as CFDictionary, &out)
        guard status == errSecSuccess, let data = out as? Data else {
            if status != errSecItemNotFound { logger.error("keychain read failed: \(status)") }
            return nil
        }
        return String(data: data, encoding: .utf8)?
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Try the installer's token file. Only succeeds unsandboxed; the sandboxed
    /// path is reported rather than swallowed so the log says *why* it missed.
    private static func readTokenFile() -> (String, String)? {
        let url = FileManager.default.homeDirectoryForCurrentUser
            .appending(path: ".local/share/mira/token")
        do {
            let raw = try String(contentsOf: url, encoding: .utf8)
            return (raw.trimmingCharacters(in: .whitespacesAndNewlines), url.path)
        } catch {
            // Expected in a sandboxed build: homeDirectoryForCurrentUser is the
            // container, so this path does not exist. Logged at debug level, but
            // NOT discarded the way the original `try?` did.
            logger.debug("token file unreadable at \(url.path, privacy: .public): \(error.localizedDescription)")
            return nil
        }
    }
}
#endif
